version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo:3.2
    networks:
      - pritunl
    ports:
      - "27017:27017"
        #    restart: always
    volumes:
      - mongo:/data/db
  pritunl:
    container_name: pritunl
    build: .
    image: pritunl
    depends_on:
      - mongo
    networks:
      - pritunl
    ports:
      - "10080:80"
      - "10443:443"
      - "1194:1194/udp"
    privileged: true
    #    restart: always

networks:
  pritunl:

volumes:
  mongo:
